spring:
  datasource:
    url: jdbc:h2:mem:capitole_challenge_database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    datasource:
      initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
